# Generated by Django 4.2.4 on 2023-09-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explanations', '0002_author_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Auteur'},
        ),
    ]
